name: Deploy to Railway

on:
  push:
    branches: [main] # Trigger on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4 # Updated from v3 to v4

      - name: Use Node.js
        uses: actions/setup-node@v4 # Updated from v3 to v4
        with:
          node-version: "20" # This is correct, keep it as is

      - name: Install Railway CLI
        run: npm i -g @railway/cli

      - name: Deploy to Railway
        run: railway up
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
